name: flutter_application
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pie_chart: ^5.3.2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  http: ^0.13.3

  cupertino_icons: ^1.0.2

  flutter_svg: ^0.22.0
  custom_text_field: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
